CREATE TABLE api_keys
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key_name   VARCHAR(255)                            NOT NULL UNIQUE,
    key_value  VARCHAR(255)                            NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    last_used  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_api_keys PRIMARY KEY (id)
);